# model 模式 debug|release
# debug模式，可以输出更加详细的日志，但是运行速度会减慢
model: debug

port: :9016

#-------------------mysql配置---------------------
mysql:
  db: process
  host: 192.168.200.18:3306
  #  host: 192.168.200.32:3306
  user: root
  #  user: qxp
  password: uyWxtvt6gCOy3VPLB3rTpa0rQ
  #  password: ZHU**jie9
  log: true



#  -------------------- log --------------------
# comply with zap log specification
log:
  level: -1
  development: false
  sampling:
    initial: 100
    thereafter: 100
  outputPath:
    - stderr
  errorOutputPath:
    - stderr

#  -------------------- internalNet --------------------
internalNet:
  timeout: 20
  maxIdleConns: 10

#-------------------redis配置-----------------
redis:
  addrs:
    - 192.168.200.18:6379
    - 192.168.200.19:6379
    - 192.168.200.20:6379
  username:
  password:
